var panoramaView;
var locations;
var panoramaMap = [];
var fovJump = 3;
var info = [];
var blocked = true;
var marker = [];
var markerMini = [];
var centerLan = 50.871599;
var centerLon =  20.631490;
var mapInited = false;
var markerImage = 'images/marker.png';
var currentMarkerImage = 'images/marker2.png';
var miniMapCenter;
var currentMarker;
var slidebars;
var isSlidebarVisible = false;
var windowManager;
var startScalingDistance;
var isScaling = false;